### ISSUE TITLE
Documentación de Software ISO-IEC-IEEE-29148

### ISSUE THREAD

**Issue by jsstiven** [afar-cmyk/ProyectoBibliotech#14]
Desarrollar la documentación requerida de este proyecto y hacerlo según la guía presentada por el tutor en la Reunión del 13/09/2021 (5:00 pm)(GTM -5).

- [x] Introducción.
- [x] Descripción General de la Aplicación.
- [x] Requerimientos Específicos.
- [x] Descripción del Diseño. ( #42 )
- [x] Gestión de la Configuración.
- [x] Pruebas.
- [x] Glosario.
- [x] Anexo.

**Comment by Jesteban247** [comment]
Se subio el documento con partes ya realizadas, sin embargo falta aclarar unas cosas en la proxima reunión

**Comment by muakarada** [comment]
Por mi parte estoy trabajando en la introducción, alcance o ámbito del sistema, solicito revisión del equipo para conocer si es concisa la información.

**Comment by jsstiven** [comment]
he estado trabajando en la nueva historia de usuario que es con base a la base de datos ya esta subida en el documento y acomode alguna información de los casos de uso que se veía mal en el documento

**Comment by afar-cmyk** [comment]
> he estado trabajando en la nueva historia de usuario que es con base a la base de datos ya esta subida en el documento y acomode alguna información de los casos de uso que se veía mal en el documento

En ese caso compañero, relacionar el avance en el _issue_ #40, voy a procurar dejar listos los _mockups_ el día de hoy, les recomiendo revisar el documento #35 , para poder darle cierre al **Sprint 1 y 2**

**Comment by afar-cmyk** [comment]
Se agregaron todos los _mockups_ que estaban contemplados en el lienzo de [Figma](https://www.figma.com/file/xTU5BRgb1jP1eUwc3Oswb9/Bibliotech-Web-design?node-id=0%3A1), de igual forma se deja un comentario en el **literal 4.1** del documento.

**Comment by afar-cmyk** [comment]
Buen trabajo compañeros!
