### ISSUE TITLE
Desarrollar pagina "index.html"

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#19]
Debe ser desarrollada en la rama **"index#19"**.

- [x] Llevar el desarrollo de la pagina **"Index.html"** conforme a lo establecido en los [Mockups](https://www.figma.com/file/xTU5BRgb1jP1eUwc3Oswb9/Bibliotech-Web-design?node-id=0%3A1).

**Importante!!** basarse en la [jerarquía del sitio y los nombres de archivo](https://docs.google.com/presentation/d/1ETA3zJ_fJ5ClMBFnPRGFU_XgEP62md20XkgyAmkx1Zg/edit?usp=sharing) que han sido previamente establecidos.

**Comment by muakarada** [comment]
Se realiza el diseño en base a los mockups de la página index, el commit es actualizado con lo trabajado

**Comment by afar-cmyk** [comment]
Buenisimo compañera, yo acabo de unir la rama en la que estaba trabajando #21 a los cambios que tu realizaste para que todos partamos desde tus adiciones.
