### ISSUE TITLE
Desarrollar pagina "trade.html"

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#20]
Debe ser desarrollada en la rama **"trade#20"**, recuerden reutilizar el código de **index.html** para el desarrollo de esta pagina.

- [x] Llevar el desarrollo de la pagina **"trade.html"** conforme a lo establecido en los [Mockups](https://www.figma.com/file/xTU5BRgb1jP1eUwc3Oswb9/Bibliotech-Web-design?node-id=0%3A1).

**Importante!!** basarse en la [jerarquía del sitio y los nombres de archivo](https://docs.google.com/presentation/d/1ETA3zJ_fJ5ClMBFnPRGFU_XgEP62md20XkgyAmkx1Zg/edit?usp=sharing) que han sido previamente establecidos.

**Comment by afar-cmyk** [comment]
Debido a un error en la estructura, se cambia el nombre de esta pagina por: trade.

**Comment by muakarada** [comment]
Se realizó la maqueta de la página trade.html según los mockups y con la funcionalidad de recibir información del libro (habilitada para el primer libro), queda establecer la petición del libro.
