### ISSUE TITLE
Interfaces gráficas de usuario

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#23]
Para entregar el **Sprint 1 y 2** es necesario llevar a cabo el desarrollo de las siguientes paginas:

- [x] #19
- [x] #20 
- [x] #21
- [x] #28 
- [x] #29

**Importante!!** basarse en la [jerarquía del sitio y los nombres de archivo](https://docs.google.com/presentation/d/1ETA3zJ_fJ5ClMBFnPRGFU_XgEP62md20XkgyAmkx1Zg/edit?usp=sharing) que han sido previamente establecidos.

**Comment by jsstiven** [comment]
se logro terminar todas las interfaces graficas para este sprint 1 y 2 aunque en la interfaz de team hay cosas que se deben de ver en grupo y se hara un reunion el dia 20/09/2021 para terminar por completo esta parte

**Comment by afar-cmyk** [comment]
Me parece perfecto, excelente trabajo muchachos!
