### ISSUE TITLE
Desarrollar pagina "about.html"

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#28]
Debe ser desarrollada en la rama **"about#28"**, recuerden reutilizar el código de **index.html** para el desarrollo de esta pagina.

- [ ] Llevar el desarrollo de la pagina **"about.html"** conforme a lo establecido en los [Mockups](https://www.figma.com/file/xTU5BRgb1jP1eUwc3Oswb9/Bibliotech-Web-design?node-id=0%3A1).

**Importante!!** basarse en la [jerarquía del sitio y los nombres de archivo](https://docs.google.com/presentation/d/1ETA3zJ_fJ5ClMBFnPRGFU_XgEP62md20XkgyAmkx1Zg/edit?usp=sharing) que han sido previamente establecidos.

**Comment by jsstiven** [comment]
realice la pagina about con los lineamiento establecidos en el mockups  junto con sus respectiva navegación

**Comment by afar-cmyk** [comment]
Se abre este issue para implementar los cambios mas cercanos a los mockups.

**Comment by jsstiven** [comment]
se termino de hacer los cambios respectivos con base a los mockups
