### ISSUE TITLE
Desarrollar pagina "team.html"

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#29]
Debe ser desarrollada en la rama **"team#29"**, recuerden reutilizar el código de **index.html** para el desarrollo de esta pagina.

- [ ] Llevar el desarrollo de la pagina **"team.html"** conforme a lo establecido en los [Mockups](https://www.figma.com/file/xTU5BRgb1jP1eUwc3Oswb9/Bibliotech-Web-design?node-id=0%3A1).

**Importante!!** basarse en la [jerarquía del sitio y los nombres de archivo](https://docs.google.com/presentation/d/1ETA3zJ_fJ5ClMBFnPRGFU_XgEP62md20XkgyAmkx1Zg/edit?usp=sharing) que han sido previamente establecidos.

**Comment by Jesteban247** [comment]
Se tiene una duda para la visualización que se informara con el equipo en la reunión del dia 20 de Septiembre, sin embargo la pagina ya esta realizada
