### ISSUE TITLE
Informe de Retrospectiva (Sprint 1 y 2)

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#35]
Desarrollar el documento **Informe de Restrospectiva** conforme a la estructura de la [**plantilla**](https://docs.google.com/document/d/1Z5qGDWNMbkVs2V8AMdY3542StswjFQ2TguTlXRr0uiY/edit?usp=sharing).

- [x] Modificar el contenido de la plantilla que fue creada en la carpeta de [Google Drive](https://drive.google.com/drive/folders/1G9H5Yhp4DACLX_iY4dTgCvNvmaP6xzUT?usp=sharing).

**Comment by jsstiven** [comment]
he estado trabajando en el informe pero desconozco varias de las cosas que piden realizar lo subiré al drive y pediré una colaboración con los demás miembros si es posible que ayuden a terminar de elaborar el informe

**Comment by afar-cmyk** [comment]
> he estado trabajando en el informe pero desconozco varias de las cosas que piden realizar lo subiré al drive con el nombre Informe de Retrospectiva (BORRADOR) se encontrara en la carpeta sprint 3 y pediré una colaboración con los demás miembros si es posible que ayuden a terminar de elaborar el informe y cuando lo hagan asignasen esta tarea por favor

En ese caso compañero, podría agregar la información que ha desarrollado en este [**documento**](https://docs.google.com/document/d/1QrLtj-6Gm4XKmXq2zSv-8mwIXiQ1fiOJvZlY7VvPhgA/edit?usp=sharing), para evitar duplicados en la carpeta de [Google Drive](https://drive.google.com/drive/folders/1G9H5Yhp4DACLX_iY4dTgCvNvmaP6xzUT?usp=sharing).

**Comment by jsstiven** [comment]
listo ya realice la recomendación

**Comment by afar-cmyk** [comment]
Se ha llevado a cabo el informe de retrospectiva semanal con apoyo de @jsstiven . Se abordaron muchos temas de lo que hemos vivido en el desarrollo del Sprint 1 y 2.
