### ISSUE TITLE
Ajustes página team.html 

### ISSUE THREAD

**Issue by muakarada** [afar-cmyk/ProyectoBibliotech#38]
- [ ] Ajustar la página team según lo propuesto en la reunión del lunes
- [ ] Actualizar en la rama de este issue los ajustes

**Comment by Jesteban247** [comment]
Hola ya realice parte de la corrección de la pagina team.html, porfa si  pueden actualizar el codigo en la pagina de la biblioteca bibliotech.biz para revisar como quedo graficamente y corregir otras cosas. Gracias

**Comment by afar-cmyk** [comment]
> Hola ya realice parte de la corrección de la pagina team.html, porfa si pueden actualizar el codigo en la pagina de la biblioteca bibliotech.biz para revisar como quedo graficamente y corregir otras cosas. Gracias

Los cambios sobre el servidor web, serán realizados **solamente** cuando se hagan adiciones a la rama _main_ (bueno, a no ser que alguien quiera subir dichos cambios con la informacion recopilada en este [documento](https://docs.google.com/presentation/d/1w8V3ZgvzLSTpYGa3Il8VS7HZJIib5tzwaYIpvsZK1h8/edit?usp=sharing).

**Comment by muakarada** [comment]
Finalmente se ajusta la página team.html, se hacen los cambios pertinentes y se une a la maqueta final :).
