### ISSUE TITLE
Historias de usuario (Sprint 3)

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#40]
Desarrollar las historias de usuario para el Sprint 3.

- [x] Revisar y modificar las historias de usuario conforme a la #41 
- [x] Subir o actualizar el documento con las **historias de usuario** a la carpeta de [Google Drive](https://drive.google.com/drive/folders/1G9H5Yhp4DACLX_iY4dTgCvNvmaP6xzUT?usp=sharing).

**Comment by afar-cmyk** [comment]
`se agregó una nueva tarea.`

**Comment by Jesteban247** [comment]
Actualizado y esta  en el drive sprint 3

**Comment by jsstiven** [comment]
se hicieron las historias pertinentes para este sprint y se actualizaron sin ningun problema
