### ISSUE TITLE
Re-estructuración de mockups (Sprint 3)

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#41]
Llevar a cabo la modificación del comportamiento del sitio que establecimos en la ultima reunión.

- [x] Modificar el comportamiento para la pagina de solicitud de préstamo del usuario final.
- [x] Re-estructurar el comportamiento del CRUD de creación y edición, para artículos y administradores.

**Comment by muakarada** [comment]
Se modifican los mockups de préstamo del sitio web del cliente, se dejan listas las vistas en Figma para exportar junto al CRUD.

**Comment by afar-cmyk** [comment]
Se modificaron los [_mockups_](https://www.figma.com/file/xTU5BRgb1jP1eUwc3Oswb9/Bibliotech-Web-design?node-id=0%3A1) conforme a lo acordado en la reunión, se remueve por completo la característica de subir imágenes al servidor.
