### ISSUE TITLE
Implementación de la lógica de negocio

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#43]
- [ ] CRUD funcional, que pueda guardar, actualizar, listar y borrar información desde o hacia un JSON.

~~(Podríamos quemar un JSON para artículos y administradores, cargarlo en los elementos del HTML)~~

**Comment by jsstiven** [comment]
se realizo la logica del crud de administradores y no solamente la api sino que apartir de una vista ya puede mandar informacion y mostrarla
