### ISSUE TITLE
Informe de retrospectiva (Sprint 3)

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#44]
Desarrollar el documento **Informe de Restrospectiva** conforme a la estructura de la [**plantilla**](https://docs.google.com/document/d/17AvMT6TEuC3t69k1zkhgcHI7Z-ZOQuHM-EDXC6Lfv68/edit?usp=sharing).

- [ ] Modificar el contenido de la plantilla que fue creada en la carpeta de [Google Drive](https://drive.google.com/drive/folders/1SHJWeQ31yk0IfNhZtky-fTVq98fPmHyH?usp=sharing).

**Comment by Jesteban247** [comment]
hola. he realizado gran adelanto en el Informe de Retrospectiva que esta en el derive del grupo. lo dejo como adelanto porque otra persona lo puede complementar

**Comment by Jesteban247** [comment]
hola. he realizado gran adelanto en el Informe de Retrospectiva que esta en el drive del grupo. Dejo como adelanto porque otra persona lo puede complementar o si quieren se puede cerrar.
