### ISSUE TITLE
Sprint 4 planning (Llenar)

### ISSUE THREAD

**Issue by muakarada** [afar-cmyk/ProyectoBibliotech#52]
Compañeros: 
Recuerden llenar en el drive el sprint planning de esta semana, cuando ya finalicen la tarea:

- Los días que les tomó hacer la tarea (Se van a ir desglosando según el desarrollo)
- Desmarcan PLANNED y ponen RELEASED (tarea completada)
- Y la fecha en la que se terminó la tarea 

[SPRINT 4 PLANNIG](https://docs.google.com/spreadsheets/d/1rC3VGW-9QYXELiJR6kS_Fr_CQJ_K9n0A/edit?usp=sharing&ouid=106254824913936710269&rtpof=true&sd=true)

- [x] Pruebas unitarias de la lógica
- [x] #61 
- [x] #62 
- [x] Historias de usuario (Sprint 4)
- [x] #90 
- [x] #59

**Comment by afar-cmyk** [comment]
Con ayuda del tutor se verificó la logica del sitio.
