### ISSUE TITLE
Pruebas unitarias de la lógica desarrollada

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#53]
Evidenciar el funcionamiento del CRUD con el servidor.

- [x] Se probó el funcionamiento del CRUD conectado a la API del servidor.

~~(Se puede evidenciar con imágenes)~~

**Comment by jsstiven** [comment]
![image](https://user-images.githubusercontent.com/87039250/135175226-569bdf10-b95f-4920-abb8-bef72a0a8261.png)
esta es la base de datos inicial como se puede ver solo hay dos registros por ahora

![image](https://user-images.githubusercontent.com/87039250/135175379-dfebc4cf-ecff-44f8-b901-d28946f0f18a.png)
esta es la api ya creada 

![image](https://user-images.githubusercontent.com/87039250/135175453-4efdc7dd-971f-49d8-b966-f08d1822497e.png)
y lo que se acabo de ver fue una vista temporal donde se estaban haciendo las pruebas de la logica empleada 

![image](https://user-images.githubusercontent.com/87039250/135175562-b0e4142b-f4b4-4838-b225-b41078f1bc04.png)
y aqui estoy a punto de presionar el primer boton para enviar la informacion y al mismo tiempo se listara en la que vemos en la parte de arriba

![image](https://user-images.githubusercontent.com/87039250/135175622-a4a6b62e-91cc-4950-99a8-4369c9aa54e5.png)
![image](https://user-images.githubusercontent.com/87039250/135175681-406b66ae-5b27-488b-b425-5f0d8dfb9586.png)
y como se puede apreciar se envio y guardo en la BD

![image](https://user-images.githubusercontent.com/87039250/135175740-b58926d6-4bba-49c8-aa0c-76b93d1e53a4.png)
aqui es donde acabe de presionar el segundo boton el cual hara una busqueda por el correo para asi eliminar a la persona que quiera de la BD cuando presione "confirmar" se eliminara

![image](https://user-images.githubusercontent.com/87039250/135175820-13dbabb0-629a-43e1-ac63-007fe46b8dcf.png)
![image](https://user-images.githubusercontent.com/87039250/135175855-bca29c56-c1c4-4849-ae9c-831a9b61109a.png)
y como se puede ver se elimino el editar tiene la misma funcion que el crear solo que se le envia un correo para hacer el proceso de edicion y con eso se tendria la logica del crud ya terminada

**Comment by afar-cmyk** [comment]
Perfecto compañero, con esto se daria por finalizado el sprint 3, por favor marcar el desarrollo en el #37 .
