### ISSUE TITLE
Listar Articulos recientes

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#65]
Asegurar la comunicación entre el sitio web y la base de datos.
- [x] Listar los **cuatro (4)** últimos artículos agregados a la **base de datos** en la pagina **Recientes**.

**Comment by jsstiven** [comment]
se logro por medio de las vistas creadas por el compañero felipe y la logica implementada por mi persona mostrar los 4 cuatro mas recientes de articulos y admins
