### ISSUE TITLE
Index.html (Migrar)

### ISSUE THREAD

**Issue by afar-cmyk** [afar-cmyk/ProyectoBibliotech#69]
Migrar los estilos, navegación y la pagina **index.html** a la carpeta Vue.js en la carpeta /[bibliotech](https://github.com/afar-cmyk/ProyectoBibliotech/tree/main/bibliotech)/, para eso se debe asegurar:

- [x] Navegación funcional
- [x] Adaptar la estructura de la pagina
- [x] Migrar los estilos
- [x] Migrar los scripts

**Comment by muakarada** [comment]
Tarea terminada.
